# Generated by Django 4.2 on 2024-09-26 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                default=django.utils.timezone.now,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                verbose_name="Ссылка на оплату",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                default=2,
                help_text="Укажите ID сессии",
                max_length=255,
                verbose_name="ID сессии",
            ),
            preserve_default=False,
        ),
    ]
