# Generated by Django 4.2 on 2024-09-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_previews/"
            ),
        ),
    ]
