# Generated by Django 4.2 on 2024-09-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_lesson_preview"),
        ("learning", "0003_course_owner_lesson_owner_alter_course_preview"),
    ]

    operations = []
