# Generated by Django 4.2 on 2024-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
