# Generated by Django 4.2 on 2024-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_alter_course_owner_alter_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
